# Generated by Django 2.2.16 on 2023-02-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230208_1254'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_not_self_follow',
        ),
    ]
